# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        run: rustup update stable

      - name: Build and test
        run: |
          cargo build --release
          cargo test --all

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings

      # https://github.com/cargo-bins/cargo-binstall
      - name: Install binary installation tool for cargo
        uses: cargo-bins/cargo-binstall@main

      # https://github.com/xd009642/tarpaulin
      - name: Install code coverage tool
        run: cargo binstall cargo-tarpaulin
        # Install takes a bit over 4 mins, while binstall 12 seconds

      - name: Measure code coverage
        run: cargo tarpaulin --out Xml

      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cobertura.xml  # The name of the coverage report generated by tarpaulin
